<?php
/**
 * Created by PhpStorm.
 * User: lihaibo
 * Date: 2016/3/26
 * Time: 20:26
 */

namespace Service\Controller;


/**
 * 后台数据接口
 * Class CmsController
 * @package Service\Controller
 * @author  : 李海波 <lihaibo123as@163.com>
 */
class LockController extends BaseController {

//    public function _initialize() {
//        parent::_initialize(); // TODO: Change the autogenerated stub
//    }

    /**
     *
     * index.php?s=/Service/Lock/index
     * @param int       $uid              教师id
     * @return json
     * {
     *     error        : "string"  // ok:成功 no:失败

     * }
     */
    public function index() {

        $lock=S('applock');

        if(empty($lock) || $lock==1){

            $this->ajaxReturn(array('error' => 'ok'));
        }else{
            $this->ajaxReturn(array('error' => 'no' ));
        }


    }
    public function update_lock() {
        $lock = $this->getRequestData('lock',2);
        S('applock',$lock);


        $this->ajaxReturn(array('error' => 'ok'));



    }
}