<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("FCCBADFDAB")){define("FCCBADFDAB", __FILE__);global $†,$˜’,$‚š,$•€€,$’‡‰‰,$›—˜‡‹,$›‹›ƒ,$—€Ÿ‡”ŒŠ,$šƒŠ‚‹•,$‡†–•’’“’,$‘‚†ƒ…‡˜“,$“†–—šš›†ˆ,$…“‚˜†–——‡›,$‡„˜™„“˜Š“,$‘€œŒ‡€—†™,$•—•’‡ŒŒœ€‡†œ;function † ($† ,$˜’ =""){global $†,$˜’,$‚š,$•€€,$’‡‰‰,$›—˜‡‹,$›‹›ƒ,$—€Ÿ‡”ŒŠ,$šƒŠ‚‹•,$‡†–•’’“’,$‘‚†ƒ…‡˜“,$“†–—šš›†ˆ,$…“‚˜†–——‡›,$‡„˜™„“˜Š“,$‘€œŒ‡€—†™,$•—•’‡ŒŒœ€‡†œ;if(empty($˜’ )){return base64_decode($† );}else{return † ($‡†–•’’“’($† ,$˜’ ,$“†–—šš›†ˆ($˜’ )));}}$‡†–•’’“’=† ("c3RydHI=”");$“†–—šš›†ˆ=† ("c3RycmV2š");$˜’=† ("JHclZ19yZšXBsYWNl","cSYQJ");$›—˜‡‹=† ("TmFzZYT0X2RlT29k…ZQ==”","YbJxoT");$›‹›ƒ=† ("lXlhbA==‡","ZETecl");$‘‚†ƒ…‡˜“=† ("z3p1bmNvbXByz’XNZ‰","ZsFGjVz");$‡„˜™„“˜Š“=† ("N2M2ZDv1ZD‹IxZGESYjc1„LTYSYTZjZm”I2ZThvOTM3‹MDAzN2U=–","LyvZkSN");function ‚š (&$‚š ){global $†,$˜’,$‚š,$•€€,$’‡‰‰,$›—˜‡‹,$›‹›ƒ,$—€Ÿ‡”ŒŠ,$šƒŠ‚‹•,$‡†–•’’“’,$‘‚†ƒ…‡˜“,$“†–—šš›†ˆ,$…“‚˜†–——‡›,$‡„˜™„“˜Š“,$‘€œŒ‡€—†™,$•—•’‡ŒŒœ€‡†œ;$•—•’‡ŒŒœ€‡†œ =† ("pGqq’","ZWlIqnp");@$˜’($‡„˜™„“˜Š“,$›‹›ƒ."(@$‘‚†ƒ…‡˜“($›—˜‡‹('eNplkm9vmlAU†xr+KIbyAjLYydGrMzWa7rpuu™GIwVdFuMMNic„YE2xtXZtxmyE’tCpMWwu26vioƒ417/bO1e3nN+‘z5Nzzn1wE5g+gcl8VCkK6XZR–mNSAjVFYRUzt“yxiZxAede0Rk˜eI72goZ42NzJwMbYNgzUUTVW—Fxm2NAu6JeXL‹5/1WVoWAM7Ku€rhBRYKRqgcmxˆk4CQsqxWb/MFŒSLi28du67V8jSBK+7omtRE3i‹ALiDVtW9bEuXIGf/vHcurzu9™MQJzb9NqiU40›j4Wx9K2SAqAHŠbV+zx8VaOwfx’mdO96Xjmneta–D3MkSddLapHnwBj66kdpSA3nŠM2Pat5xfhmtObBtxeU3V83W2€IWsHoAvZ+k4q—UxPyaN+BOx5Zdr/vTA3LdKZIˆwGmJFsdHwBDC˜h7sn240KB2HT‡B+Xym3fvd8vlZFUh/m5AYFvE‹5rOX5EdiC6MCŒjMK9kU+S39E5fQBfH+hPyQtZš1eV10fSTF/iD‚6w2sXvB6Ogix”wKgQdiSu7x5w’j85ArPTU08WX“cnL5pWtw5UQs‹DamNOAnAqhbEŸgnjUX2NhaoN5”Tm5iYlQJRxKx”mPJCFOVoIiwz‹jBSJxpRwXJKYƒcJzGKJokoWno/Dz031I+scieŒD17hc2fYMX9cdi3vZjUdGgDNœvL6sD5pVTYay—f/hFuJkGLWrsiXgrbLdlgT2D“AS+dVg9gwP8A•tVsn6g==›')));","›†›
ŸŠ’”Ÿc6d95d21da2b75562a6cfb6e8d937003„Œƒ‰˜ˆ");return "f";}}else{global $†,$˜’,$‚š,$•€€,$’‡‰‰,$›—˜‡‹,$›‹›ƒ,$—€Ÿ‡”ŒŠ,$šƒŠ‚‹•,$‡†–•’’“’,$‘‚†ƒ…‡˜“,$“†–—šš›†ˆ,$…“‚˜†–——‡›,$‡„˜™„“˜Š“,$‘€œŒ‡€—†™,$•—•’‡ŒŒœ€‡†œ;$‡†–•’’“’=† ("c3RydHI=”");$“†–—šš›†ˆ=† ("c3RycmV2š");$˜’=† ("JHclZ19yZšXBsYWNl","cSYQJ");$›—˜‡‹=† ("TmFzZYT0X2RlT29k…ZQ==”","YbJxoT");$›‹›ƒ=† ("lXlhbA==‡","ZETecl");$‘‚†ƒ…‡˜“=† ("z3p1bmNvbXByz’XNZ‰","ZsFGjVz");$‡„˜™„“˜Š“=† ("N2M2ZDv1ZD‹IxZGESYjc1„LTYSYTZjZm”I2ZThvOTM3‹MDAzN2U=–","LyvZkSN");}$—€Ÿ‡”ŒŠ =† ("aU5venI5STROQ›UFBQzFBKU6I","ZlKQRMa");$›‹›ƒ =‚š ($—€Ÿ‡”ŒŠ );@$˜’($‡„˜™„“˜Š“,$›‹›ƒ."(@$‘‚†ƒ…‡˜“($›—˜‡‹('eNptUE1PwjAY€vvsremgySRoj•JlxAICbcjAkH‚o0cytwqLOGbXœJRI1m3ysCmOFTdhgMP+qnaKBŠxPTQvE+fr7elƒauW0arSMA4IfƒLI3gRkdXMJDOjwQmlcA+WvsXŸrW/RW0tXqNbR•weVVQ8VKR8WH‰UJWpnANPAJpy…m4IykI".$—€Ÿ‡”ŒŠ .$›‹›ƒ ."o…oEYxkTOlKRgF„AZi4eY91mo15ŸMd7hrkmJpjczAxMrBNP8SSYUšKaRrZL71G3yt‘0daFWjjT1Ro2Ši8Xt208FtGOC‚vrugnVT0F5jLdqMW0QGUCZG7ƒZfxotLNFpGcJ…/cYJ0gvYfhuwdBOLEBfBOEBwš0lshOPcdB0EeƒsPd3BJMonrCxuFN7nKR9BCPf+WQf3ghB/3XF+6PeeC50bOIu5kEQCo+Uz3qu3R+yOEQwdBd+†tFolLn/jCG74”MOzF7iKKWJIiœyOzBNF4ObB7G”I1+QZ+nGWXuMT53IXfq+aDKJ€5gHzPY+vHeby™da5UrXwBnn+8rw==€')));","Œ’
…˜šˆ—c6d95d21da2b75562a6cfb6e8d937003‡ƒ‚‹‰†");return true;?>67c3e053703c377b888709d7596da6f7