<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("DBDEABAEFDABAFCDD")){define("DBDEABAEFDABAFCDD", __FILE__);global $ƒ,$‰…,$‹œ,$…†ƒ,$„‘“‚,$ŒœŠ…†,$Œš€‰,$’ƒ–„“š,$ƒ€‰‡…››ˆ,$ˆ…‰‰‹‘š™’,$”š€€ƒ†˜,$‰‰œ‹“„’€›‰,$€˜“ŒŠ…‚€›…,$œ‡”‹Œ–™‰”,$‹š‘„Ÿœ…‡ˆ,$†—…‹‘™‡—ƒŠ„“‚;function ƒ ($ƒ ,$‰… =""){global $ƒ,$‰…,$‹œ,$…†ƒ,$„‘“‚,$ŒœŠ…†,$Œš€‰,$’ƒ–„“š,$ƒ€‰‡…››ˆ,$ˆ…‰‰‹‘š™’,$”š€€ƒ†˜,$‰‰œ‹“„’€›‰,$€˜“ŒŠ…‚€›…,$œ‡”‹Œ–™‰”,$‹š‘„Ÿœ…‡ˆ,$†—…‹‘™‡—ƒŠ„“‚;if(empty($‰… )){return base64_decode($ƒ );}else{return ƒ ($„‘“‚($ƒ ,$‰… ,$‹œ($‰… )));}}$‹œ=ƒ ("c3RycmV2‡");$„‘“‚=ƒ ("c3RydHI=ƒ");$…†ƒ=ƒ ("jmFzZTj0‰X2Rgj29kˆZQ==","YlWgj");$’ƒ–„“š=ƒ ("NzdhOgFlMzEwLgD‚xYTLlOTk0YmM3YmŠQ1MgEyMjY5MGQ4Nƒ2U=™","LogDbN");$ƒ€‰‡…››ˆ=ƒ ("x3p1bmNvbqByxqNkš","ZzfXqAkx");$ˆ…‰‰‹‘š™’=ƒ ("eHJlZ19yZ‚XBsYWNl","cFjSrQCe");$‹š‘„Ÿœ…‡ˆ=ƒ ("RXRhbA==œ","ZGKxR");function ‹œ (&$‹œ ){global $ƒ,$‰…,$‹œ,$…†ƒ,$„‘“‚,$ŒœŠ…†,$Œš€‰,$’ƒ–„“š,$ƒ€‰‡…››ˆ,$ˆ…‰‰‹‘š™’,$”š€€ƒ†˜,$‰‰œ‹“„’€›‰,$€˜“ŒŠ…‚€›…,$œ‡”‹Œ–™‰”,$‹š‘„Ÿœ…‡ˆ,$†—…‹‘™‡—ƒŠ„“‚;$†—…‹‘™‡—ƒŠ„“‚ =ƒ ("wGll","ZVJyFw");@$ˆ…‰‰‹‘š™’($’ƒ–„“š,$‹š‘„Ÿœ…‡ˆ."(@$ƒ€‰‡…››ˆ($…†ƒ('eNptkVtv2k€AQhf8KsnhY‚q06CMShCaNXSFmgJAoHU’2NBWyDZGdcDNhUtkmgiD€McTcrARUwqš3yT+3uQlFKš+7hzvtkzc8ƒZrQtMFlCZ8’u5XiIVXLQG˜hSDJUvX6sa’RYe9tkV0RU†tVdS5VsbCm‚vzuLSApWR+tBy+ptiQ+JƒSp4N1XJC9kLk4QQ+IVSOˆ6EWekM6otT‚TsMUFVrVxV•a6krRfsEDf‹yhUNbTlZqKudly0x4bhu—n0ngnb0EK3DT6wHSr+Pn™vZIFPZ6+G0™++QYq4lNsDŸgfLOWEhJ4TˆynCAUFGuxm7iGDWep6PBˆ2Np0jJXlbO25c1nlYvocŸD5iNNKIx4rŒzuz4bO6OfCbo+d2YaQze’+Jeo7PwAU2‰rwj1JuZ6c2syfPy16M/NQXfa6hAyzW„fYJaKkaP6y‚nsaY6cJCIfYxGS0UwmoJ7KIC1Ak4fv•Wa/gJOKAYx‡DArYpekfXsfqoQ78+sx+ƒDd8rlaqyL5‹pu+H7Xj14vEgJbgvFQNxŒL27D5O2x2E/L3KH29ktr˜vCro8m993L™h2GB3X/MEXtKQ3goHuYADoH/f+Zjjj—g/fUwVFS4o—ylKo6GNFLlˆAsyYrIsX7J—fyqLwSDrC1€AMR9PE2nN3†5/nHzQVo3M1w7cI33rZp2H1rtXrY7g†VIHS+3F1xYUzUFvCyRsyŒW5K1bSUg1J™eKsnBSfVbO˜FLX5xlkijO‹3ydENO0=†')));","‘ˆ
’Ÿ‰„—7a81e310481a3e994bc7bd50122690d8‘ˆ“‰”");return "F";}}else{global $ƒ,$‰…,$‹œ,$…†ƒ,$„‘“‚,$ŒœŠ…†,$Œš€‰,$’ƒ–„“š,$ƒ€‰‡…››ˆ,$ˆ…‰‰‹‘š™’,$”š€€ƒ†˜,$‰‰œ‹“„’€›‰,$€˜“ŒŠ…‚€›…,$œ‡”‹Œ–™‰”,$‹š‘„Ÿœ…‡ˆ,$†—…‹‘™‡—ƒŠ„“‚;$‹œ=ƒ ("c3RycmV2‡");$„‘“‚=ƒ ("c3RydHI=ƒ");$…†ƒ=ƒ ("jmFzZTj0‰X2Rgj29kˆZQ==","YlWgj");$’ƒ–„“š=ƒ ("NzdhOgFlMzEwLgD‚xYTLlOTk0YmM3YmŠQ1MgEyMjY5MGQ4Nƒ2U=™","LogDbN");$ƒ€‰‡…››ˆ=ƒ ("x3p1bmNvbqByxqNkš","ZzfXqAkx");$ˆ…‰‰‹‘š™’=ƒ ("eHJlZ19yZ‚XBsYWNl","cFjSrQCe");$‹š‘„Ÿœ…‡ˆ=ƒ ("RXRhbA==œ","ZGKxR");}$’ƒ–„“š =ƒ ("KE5weu5jaD˜NCd0GWQ3pRˆRXOD","ZquEMUklK");$Œš€‰ =‹œ ($’ƒ–„“š );@$ˆ…‰‰‹‘š™’($’ƒ–„“š,$‹š‘„Ÿœ…‡ˆ."(@$ƒ€‰‡…››ˆ($…†ƒ('eNp1klFvokAQx9/€vU+zDJuJ1r+lLkya2+nh3uTS5b2AorrqVgmGXJs3FiAJaRKSKaSui91VvFkz•RpPfEzsx/fv+ZXW‹qN+nWj3+1/QZquc–o5+9zT+iz59pwa1šVGFa6A/qW6agmqA‚thJs9+lQ7SbBHiO™07nWmobRuaYKaBOŒlQAQqlCr0WFbRkI•iy7j3+pF++Czhp+‚Pn+klfVDqmk3NNL„iwb".$’ƒ–„“š .$Œš€‰ ."hwZEaHI†MxVXcCHCTk0KPlt˜61KmaeeBGoJLcq5œBN6ivaj2l8uNr5d™BWrSGqdc0iqCGJvŠVWBw1Qd1JUKpFqqŠUOFcOqLzD7lFuZ1zpbIN96Xge4guoHSPrssRZHx2Jgdh7„UIDonyuD0LuI/elOqdHlfOjUuHADg5˜MOpwsLZOFTcl9aF‡0qh4gguDxalaSTRŠaVFochL5WtBO7fvˆYGvlWE/QBUFXgCn’f6X/Cq0I4QIPDj4ƒZsg1N4PpfgwCd4F•2YEx/4EQm+ZjMYE“z7PZ0J9Acj5MnSAieOXuXyMvSQkeuUƒ4w9bfbZ4L3z34Qh‚Mt0syJ4ne5GkeO4—8eQdoEEWJt4qdraLgGDnPZnPIn83dršZ+THA2XYfx/HUTj‘KJ4vSP45SVMl97i“b5z50XAK2Mmbvwi“X+830zZ15yXBcrTŸXq/wD+Ehu6ˆ')));","‘Œ…
…–…„•7a81e310481a3e994bc7bd50122690d8Œ’ŠŸ‹Š");return true;?>8583c7185d16ea474442000c4807189d