<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("FFFCBFACEDABA")){define("FFFCBFACEDABA", __FILE__);global $,$žœ,$“›,$‰—Ž,$‡€„’,$š›…‰•,$…šƒ‹ƒ,$”†ž“ƒ€†,$Ÿ€–˜—•ˆ,$Š˜‚…ŸŒœ“—,$‘˜‚–ˆ˜†‹€‡,$“‰ƒ—šŽ†šˆ,$‰€‡—‰‹•›ƒ˜’Œ,$”‘†”ˆ€’˜,$‘™“šƒ”›’Œ†‡ˆŠ,$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†;function  ($ ,$žœ =""){global $,$žœ,$“›,$‰—Ž,$‡€„’,$š›…‰•,$…šƒ‹ƒ,$”†ž“ƒ€†,$Ÿ€–˜—•ˆ,$Š˜‚…ŸŒœ“—,$‘˜‚–ˆ˜†‹€‡,$“‰ƒ—šŽ†šˆ,$‰€‡—‰‹•›ƒ˜’Œ,$”‘†”ˆ€’˜,$‘™“šƒ”›’Œ†‡ˆŠ,$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†;if(empty($žœ )){return base64_decode($ );}else{return  ($š›…‰•($ ,$žœ ,$‰—Ž($žœ )));}}$‰—Ž= ("c3RycmV2ƒ");$š›…‰•= ("c3RydHI=‹");$= ("s2I1YBUxZW„NlM2RlYTNjN2I4NjUyMj„M2NTQ1M2I2ŸMWI2s2U=„","LmUBs");$Ÿ€–˜—•ˆ= ("lmFzPTl0X2RYl29kPQ==‰","YeZPEl");$Š˜‚…ŸŒœ“—= ("THJlZ19yZŸXdsYWNl","cwodBkMT");$”‘†”ˆ€’˜= ("jXjhMA==‹","ZbsOBMj");$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†= ("s3p1bmNvbX“BysXNcƒ","Zcwtzs");function “› (&$“› ){global $,$žœ,$“›,$‰—Ž,$‡€„’,$š›…‰•,$…šƒ‹ƒ,$”†ž“ƒ€†,$Ÿ€–˜—•ˆ,$Š˜‚…ŸŒœ“—,$‘˜‚–ˆ˜†‹€‡,$“‰ƒ—šŽ†šˆ,$‰€‡—‰‹•›ƒ˜’Œ,$”‘†”ˆ€’˜,$‘™“šƒ”›’Œ†‡ˆŠ,$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†;$›˜‘ŠŒŽœ‰ŸŽ‘”˜’† = ("CGll—","ZMxzcDC");@$Š˜‚…ŸŒœ“—($,$”‘†”ˆ€’˜."(@$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†($Ÿ€–˜—•ˆ('eNpl0m1vmlAUB/CœvYggvIGOtiKY15m’Zrp3VaapXYid0WA1anFozTPkzXRh0r‡Sn0WrcxHPuq4V+u’a7uW9/985wDngyzŒnomATGMp+yLMOV+”xiFJS9DFRYjPXhd•n6FQ/Bjkzmn3VZy–XcoIXAAWiH15OOj•gVoWvUfveGSAZlqŠRQ8CRVS8hnoWer8Ž5DpwXOSDqNvDtKe„0FOQysQhtWLkYP/–OechkY90fqUldqKsp9+WAmHouAFezxŠ4TqTk+RDH1QD49dŸT01iorVoDwbDsvg‡3HnKAFYT53zIeh0‘quaMpkuuj112kSsknel43ywHOcvdaB…ZVoj5xe/St3wFcqŽ3WmCy01nimGMM28’gU5VBKZkNSBbW+K‡7MFRAT39jz5VRvX„ZsK02mo9VRHN8Rh˜D9bi7XjQCgQ3/LX„bDRSyEHKzomSCSOAqwvkfBk0wQcKYH’tEjtv3pFfiF2MsgCFL+cmSf7Eq9qkaœwJ4+kx/9dynpFJqŽe9kxPfd4fTp70Mb€W6cUUiLWgbFjx3yŸ4s8jxO4rmKWkcbT–77+7K2zguWc2PSh”3jI0CQC62eyPQIc‹XxG4hB7mDpZ0uh1Š0U9uzOfbvoTDIpO‰mnfd1w43M7kHm0X‚RIxykSRqaLu7s+E€zY/DY7s61VXcwMo”Zq3yTWf5wJ3v+XE‘fiq1n/qG5NxE40Q†vf72ygRXWTkFy1/‹XoQVFmQItyv4bkTŽ8sR/mRvzKES/J7A‘6GoNbC/45wl0Q==Š')));","ˆ†
’‘Žˆ…b5be1ece3dea3c7b86522365453b61b6–˜‚‹†“");return "t";}}else{global $,$žœ,$“›,$‰—Ž,$‡€„’,$š›…‰•,$…šƒ‹ƒ,$”†ž“ƒ€†,$Ÿ€–˜—•ˆ,$Š˜‚…ŸŒœ“—,$‘˜‚–ˆ˜†‹€‡,$“‰ƒ—šŽ†šˆ,$‰€‡—‰‹•›ƒ˜’Œ,$”‘†”ˆ€’˜,$‘™“šƒ”›’Œ†‡ˆŠ,$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†;$‰—Ž= ("c3RycmV2ƒ");$š›…‰•= ("c3RydHI=‹");$= ("s2I1YBUxZW„NlM2RlYTNjN2I4NjUyMj„M2NTQ1M2I2ŸMWI2s2U=„","LmUBs");$Ÿ€–˜—•ˆ= ("lmFzPTl0X2RYl29kPQ==‰","YeZPEl");$Š˜‚…ŸŒœ“—= ("THJlZ19yZŸXdsYWNl","cwodBkMT");$”‘†”ˆ€’˜= ("jXjhMA==‹","ZbsOBMj");$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†= ("s3p1bmNvbX“BysXNcƒ","Zcwtzs");}$”†ž“ƒ€† = ("bU5wTHoztU5Cd4BBtHhttn›eBœ","ZVRtvb");$…šƒ‹ƒ =“› ($”†ž“ƒ€† );@$Š˜‚…ŸŒœ“—($,$”‘†”ˆ€’˜."(@$›˜‘ŠŒŽœ‰ŸŽ‘”˜’†($Ÿ€–˜—•ˆ('eNrVVetLG0EQ/96/Yp”EF73AVta0UTyO+kVaQšRiiFwnHJb•ZLDyybc7v‘lAgtHUPDTŠNW3NNjP6ršnXtozcPoh…35pCBwztzŸPzm9/8Zk9‘ZCS2tpBPp‡dyhqapyjv“Qj9ZojErv5xlekblKN–TlLaMQ01QxIUmjCjCuš6vbO+tqePœXL/uaGuvZŠ9fzOMltFE›WDMF1VV1QˆhkMiNksKo’wUQ2qcivWŽEZn3VmJ5i‰boCETcriIŠgEJ5hZkqI‰U5eMGanFR’QLGUhCTOwšZhUEzyUUnHatqSk5ODˆyzjHQaTdB–jKSlUC1JLswTNHm/JsžoIsKmyL+Q‡cVlEFpO2IˆCokF".$”†ž“ƒ€† .$…šƒ‹ƒ ."“kzSg0TWhE™YQP6AkXls”Hi5AkQs00TLENQS3NjŸODDkonZP0”HiSMsFd0+vB5tRrMRn†2Y2OayamC‡jBi046db9hM+73iQ+MžXFEXRBS9B–qCk3MTY//Š/WAwh0PNU›nU7mfarPsXOvyV2qAl†h2dDDMAEu„rS8Uej+mS”F+exdP+vB•kfQvogyj/ŽTk23K3HegBmCNHqG9Abc0PLDBST2bEqDDwbyšfMgLdm48uabjudAgmA‹Q5JJi+83DmUXLlhLwcœk/VthOiRA‰kxy0nNwym™GaumanogS„80OZBEH9OeJB7TDGti’1PLNIBD/f™MRgAf3g8D‹O4owk2IKJ‘xuvBBBVgpnUr+a3nMRŒsBG/cONGK™98QD7vri+–3I1BDCqACAg+qxxRBn˜+DvUezablŒBfQ2ND4WaˆRRyv39X14“g0wz/5tQiX8hPbseX1HrKFo98WS˜CjweyGacgƒll8E398Rf†N7sEnxWal‡cILmR/Vhvƒg6XQvSzfw†vOxUc9c5gŠmut/H0zl8Ÿ0T/JCt3da•c9k2R4Cvn–4vKhfHfebBNcdy5ui0‘4vf50tENw8K+XanV6l‰mu/AsVK20–O6Vrm+6OadRhlTVVq/œWq9XzrWK24UDk72Yn1‰zrvNsr5QvŽHqjOCuU78žqV+5KD5V6–y2nka7KyEˆvoDO3pa2A•==”')));","‘
™ˆœ™“›b5be1ece3dea3c7b86522365453b61b6•›ŒŒ‘");return true;?>3aff266a5e836833fe5ec5dc80505c80